/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ArtPortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imagePath' : IDL.Text,
  'isLive' : IDL.Bool,
});
export const DesignPortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'figmaUrl' : IDL.Text,
  'client' : IDL.Text,
  'title' : IDL.Text,
  'imageData' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'year' : IDL.Text,
  'description' : IDL.Text,
  'isLive' : IDL.Bool,
  'videoUrl' : IDL.Text,
});
export const LectureItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'description' : IDL.Text,
  'isLive' : IDL.Bool,
  'prototypeUrl' : IDL.Text,
});
export const ResearchItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imagePath' : IDL.Text,
  'description' : IDL.Text,
  'isLive' : IDL.Bool,
});
export const StudentWorkItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'year' : IDL.Text,
  'isLive' : IDL.Bool,
  'student' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArtItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addDesignPortfolio' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addLecture' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addResearchItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addStudentWork' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteArtItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteDesignPortfolio' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLecture' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteResearchItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStudentWork' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCvLink' : IDL.Func([], [IDL.Text], ['query']),
  'getProfessionalNarrative' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'healthCheck' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllArtItems' : IDL.Func([], [IDL.Vec(ArtPortfolioItem)], ['query']),
  'listAllDesignPortfolio' : IDL.Func(
      [],
      [IDL.Vec(DesignPortfolioItem)],
      ['query'],
    ),
  'listAllLectures' : IDL.Func([], [IDL.Vec(LectureItem)], ['query']),
  'listAllResearchItems' : IDL.Func([], [IDL.Vec(ResearchItem)], ['query']),
  'listAllStudentWorks' : IDL.Func([], [IDL.Vec(StudentWorkItem)], ['query']),
  'listLiveArtItems' : IDL.Func([], [IDL.Vec(ArtPortfolioItem)], ['query']),
  'listLiveDesignPortfolio' : IDL.Func(
      [],
      [IDL.Vec(DesignPortfolioItem)],
      ['query'],
    ),
  'listLiveLectures' : IDL.Func([], [IDL.Vec(LectureItem)], ['query']),
  'listLiveResearchItems' : IDL.Func([], [IDL.Vec(ResearchItem)], ['query']),
  'listLiveStudentWorks' : IDL.Func([], [IDL.Vec(StudentWorkItem)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setArtItemLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'setCvLink' : IDL.Func([IDL.Text], [], []),
  'setDesignPortfolioLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'setLectureLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'setProfessionalNarrative' : IDL.Func([IDL.Text], [], []),
  'setResearchItemLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'setStudentWorkLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ArtPortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imagePath' : IDL.Text,
    'isLive' : IDL.Bool,
  });
  const DesignPortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'figmaUrl' : IDL.Text,
    'client' : IDL.Text,
    'title' : IDL.Text,
    'imageData' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'year' : IDL.Text,
    'description' : IDL.Text,
    'isLive' : IDL.Bool,
    'videoUrl' : IDL.Text,
  });
  const LectureItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'description' : IDL.Text,
    'isLive' : IDL.Bool,
    'prototypeUrl' : IDL.Text,
  });
  const ResearchItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imagePath' : IDL.Text,
    'description' : IDL.Text,
    'isLive' : IDL.Bool,
  });
  const StudentWorkItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'year' : IDL.Text,
    'isLive' : IDL.Bool,
    'student' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArtItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addDesignPortfolio' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addLecture' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addResearchItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addStudentWork' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteArtItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteDesignPortfolio' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLecture' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteResearchItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStudentWork' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCvLink' : IDL.Func([], [IDL.Text], ['query']),
    'getProfessionalNarrative' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'healthCheck' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllArtItems' : IDL.Func([], [IDL.Vec(ArtPortfolioItem)], ['query']),
    'listAllDesignPortfolio' : IDL.Func(
        [],
        [IDL.Vec(DesignPortfolioItem)],
        ['query'],
      ),
    'listAllLectures' : IDL.Func([], [IDL.Vec(LectureItem)], ['query']),
    'listAllResearchItems' : IDL.Func([], [IDL.Vec(ResearchItem)], ['query']),
    'listAllStudentWorks' : IDL.Func([], [IDL.Vec(StudentWorkItem)], ['query']),
    'listLiveArtItems' : IDL.Func([], [IDL.Vec(ArtPortfolioItem)], ['query']),
    'listLiveDesignPortfolio' : IDL.Func(
        [],
        [IDL.Vec(DesignPortfolioItem)],
        ['query'],
      ),
    'listLiveLectures' : IDL.Func([], [IDL.Vec(LectureItem)], ['query']),
    'listLiveResearchItems' : IDL.Func([], [IDL.Vec(ResearchItem)], ['query']),
    'listLiveStudentWorks' : IDL.Func(
        [],
        [IDL.Vec(StudentWorkItem)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setArtItemLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'setCvLink' : IDL.Func([IDL.Text], [], []),
    'setDesignPortfolioLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'setLectureLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'setProfessionalNarrative' : IDL.Func([IDL.Text], [], []),
    'setResearchItemLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'setStudentWorkLive' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };