/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DesignPortfolioItem {
    id: bigint;
    figmaUrl: string;
    client: string;
    title: string;
    pdfData: string;
    imageData: string;
    tags: Array<string>;
    year: string;
    description: string;
    isLive: boolean;
    videoUrl: string;
}
export interface ResearchItem {
    id: bigint;
    title: string;
    imagePath: string;
    description: string;
    isLive: boolean;
}
export interface StudentWorkItem {
    id: bigint;
    photoData: string;
    pdfData: string;
    studentName: string;
    description: string;
    isLive: boolean;
}
export interface LectureItem {
    id: bigint;
    title: string;
    duration: string;
    pdfData: string;
    description: string;
    isLive: boolean;
    prototypeUrl: string;
}
export interface ArtPortfolioItem {
    id: bigint;
    title: string;
    imagePath: string;
    isLive: boolean;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addArtItem(title: string, imagePath: string): Promise<bigint>;
    addDesignPortfolio(title: string, client: string, year: string, tags: Array<string>, figmaUrl: string, imageData: string, videoUrl: string, description: string, pdfData: string): Promise<bigint>;
    addLecture(title: string, prototypeUrl: string, description: string, duration: string, pdfData: string): Promise<bigint>;
    addResearchItem(title: string, description: string, imagePath: string): Promise<bigint>;
    addStudentWork(studentName: string, description: string, photoData: string, pdfData: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteArtItem(id: bigint): Promise<boolean>;
    deleteDesignPortfolio(id: bigint): Promise<boolean>;
    deleteLecture(id: bigint): Promise<boolean>;
    deleteResearchItem(id: bigint): Promise<boolean>;
    deleteStudentWork(id: bigint): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCvLink(): Promise<string>;
    getCvPdf(): Promise<string>;
    getProfessionalNarrative(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    healthCheck(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAllArtItems(): Promise<Array<ArtPortfolioItem>>;
    listAllDesignPortfolio(): Promise<Array<DesignPortfolioItem>>;
    listAllLectures(): Promise<Array<LectureItem>>;
    listAllResearchItems(): Promise<Array<ResearchItem>>;
    listAllStudentWorks(): Promise<Array<StudentWorkItem>>;
    listLiveArtItems(): Promise<Array<ArtPortfolioItem>>;
    listLiveDesignPortfolio(): Promise<Array<DesignPortfolioItem>>;
    listLiveLectures(): Promise<Array<LectureItem>>;
    listLiveResearchItems(): Promise<Array<ResearchItem>>;
    listLiveStudentWorks(): Promise<Array<StudentWorkItem>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setArtItemLive(id: bigint, isLive: boolean): Promise<boolean>;
    setCvLink(link: string): Promise<void>;
    setCvPdf(data: string): Promise<void>;
    setDesignPortfolioLive(id: bigint, isLive: boolean): Promise<boolean>;
    setLectureLive(id: bigint, isLive: boolean): Promise<boolean>;
    setProfessionalNarrative(narrative: string): Promise<void>;
    setResearchItemLive(id: bigint, isLive: boolean): Promise<boolean>;
    setStudentWorkLive(id: bigint, isLive: boolean): Promise<boolean>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addArtItem(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addArtItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArtItem(arg0, arg1);
            return result;
        }
    }
    async addDesignPortfolio(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDesignPortfolio(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDesignPortfolio(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addLecture(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLecture(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLecture(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addResearchItem(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addResearchItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResearchItem(arg0, arg1, arg2);
            return result;
        }
    }
    async addStudentWork(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudentWork(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudentWork(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteArtItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArtItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArtItem(arg0);
            return result;
        }
    }
    async deleteDesignPortfolio(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDesignPortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDesignPortfolio(arg0);
            return result;
        }
    }
    async deleteLecture(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLecture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLecture(arg0);
            return result;
        }
    }
    async deleteResearchItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResearchItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResearchItem(arg0);
            return result;
        }
    }
    async deleteStudentWork(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentWork(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentWork(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCvLink(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCvLink();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCvLink();
            return result;
        }
    }
    async getCvPdf(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCvPdf();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCvPdf();
            return result;
        }
    }
    async getProfessionalNarrative(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfessionalNarrative();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfessionalNarrative();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async healthCheck(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllArtItems(): Promise<Array<ArtPortfolioItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllArtItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllArtItems();
            return result;
        }
    }
    async listAllDesignPortfolio(): Promise<Array<DesignPortfolioItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllDesignPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllDesignPortfolio();
            return result;
        }
    }
    async listAllLectures(): Promise<Array<LectureItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllLectures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllLectures();
            return result;
        }
    }
    async listAllResearchItems(): Promise<Array<ResearchItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllResearchItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllResearchItems();
            return result;
        }
    }
    async listAllStudentWorks(): Promise<Array<StudentWorkItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllStudentWorks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllStudentWorks();
            return result;
        }
    }
    async listLiveArtItems(): Promise<Array<ArtPortfolioItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLiveArtItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLiveArtItems();
            return result;
        }
    }
    async listLiveDesignPortfolio(): Promise<Array<DesignPortfolioItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLiveDesignPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLiveDesignPortfolio();
            return result;
        }
    }
    async listLiveLectures(): Promise<Array<LectureItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLiveLectures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLiveLectures();
            return result;
        }
    }
    async listLiveResearchItems(): Promise<Array<ResearchItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLiveResearchItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLiveResearchItems();
            return result;
        }
    }
    async listLiveStudentWorks(): Promise<Array<StudentWorkItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLiveStudentWorks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLiveStudentWorks();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setArtItemLive(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setArtItemLive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setArtItemLive(arg0, arg1);
            return result;
        }
    }
    async setCvLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCvLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCvLink(arg0);
            return result;
        }
    }
    async setCvPdf(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCvPdf(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCvPdf(arg0);
            return result;
        }
    }
    async setDesignPortfolioLive(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setDesignPortfolioLive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDesignPortfolioLive(arg0, arg1);
            return result;
        }
    }
    async setLectureLive(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setLectureLive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLectureLive(arg0, arg1);
            return result;
        }
    }
    async setProfessionalNarrative(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfessionalNarrative(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfessionalNarrative(arg0);
            return result;
        }
    }
    async setResearchItemLive(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setResearchItemLive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setResearchItemLive(arg0, arg1);
            return result;
        }
    }
    async setStudentWorkLive(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setStudentWorkLive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStudentWorkLive(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
